/*
 * This file is generated by jOOQ.
*/
package com.jooqGenerated.tables.records;


import com.jooqGenerated.tables.Parent;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParentRecord extends UpdatableRecordImpl<ParentRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1147337063;

    /**
     * Setter for <code>jooq.parent.parentId</code>.
     */
    public void setParentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq.parent.parentId</code>.
     */
    public Integer getParentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooq.parent.studentId</code>.
     */
    public void setStudentid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq.parent.studentId</code>.
     */
    public Integer getStudentid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Parent.PARENT.PARENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Parent.PARENT.STUDENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getParentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStudentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParentRecord value1(Integer value) {
        setParentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParentRecord value2(Integer value) {
        setStudentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParentRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParentRecord
     */
    public ParentRecord() {
        super(Parent.PARENT);
    }

    /**
     * Create a detached, initialised ParentRecord
     */
    public ParentRecord(Integer parentid, Integer studentid) {
        super(Parent.PARENT);

        set(0, parentid);
        set(1, studentid);
    }
}
