/*
 * This file is generated by jOOQ.
*/
package com.jooqGenerated;


import com.jooqGenerated.tables.Parent;
import com.jooqGenerated.tables.Student;
import com.jooqGenerated.tables.records.ParentRecord;
import com.jooqGenerated.tables.records.StudentRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>jooq</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ParentRecord, Integer> IDENTITY_PARENT = Identities0.IDENTITY_PARENT;
    public static final Identity<StudentRecord, Integer> IDENTITY_STUDENT = Identities0.IDENTITY_STUDENT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ParentRecord> KEY_PARENT_PRIMARY = UniqueKeys0.KEY_PARENT_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = UniqueKeys0.KEY_STUDENT_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ParentRecord, StudentRecord> PARENT_IBFK_1 = ForeignKeys0.PARENT_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ParentRecord, Integer> IDENTITY_PARENT = createIdentity(Parent.PARENT, Parent.PARENT.PARENTID);
        public static Identity<StudentRecord, Integer> IDENTITY_STUDENT = createIdentity(Student.STUDENT, Student.STUDENT.STUDENTID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ParentRecord> KEY_PARENT_PRIMARY = createUniqueKey(Parent.PARENT, "KEY_parent_PRIMARY", Parent.PARENT.PARENTID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = createUniqueKey(Student.STUDENT, "KEY_student_PRIMARY", Student.STUDENT.STUDENTID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ParentRecord, StudentRecord> PARENT_IBFK_1 = createForeignKey(com.jooqGenerated.Keys.KEY_STUDENT_PRIMARY, Parent.PARENT, "parent_ibfk_1", Parent.PARENT.STUDENTID);
    }
}
