/*
 * This file is generated by jOOQ.
*/
package com.jooqGenerated;


import com.jooqGenerated.tables.Parent;
import com.jooqGenerated.tables.Student;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.parent</code>.
     */
    public static final Parent PARENT = com.jooqGenerated.tables.Parent.PARENT;

    /**
     * The table <code>jooq.student</code>.
     */
    public static final Student STUDENT = com.jooqGenerated.tables.Student.STUDENT;
}
